[project]
name = "fileshare"
version = "0.1.0"
description = "Send and receive files over the network."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "attrs==26.1.0",
    "asgiref==3.12.1",
    "autobahn==26.7.1",
    "automat==25.4.16",
    "cffi==2.0.0",
    "channels==4.3.2",
    "constantly==23.10.4",
    "cryptography==45.0.6",
    "daphne==4.2.3",
    "django==6.0.6",
    "hyperlink==21.0.0",
    "idna==3.18",
    "incremental==24.11.0",
    "pyasn1==0.6.4",
    "pyasn1-modules==0.4.2",
    "pycparser==3.0",
    "python-dotenv==1.2.2",
    "pyopenssl==25.1.0",
    "service-identity==24.2.0",
    "sqlparse==0.5.5",
    "tomli==2.4.1",
    "twisted==25.5.0",
    "txaio==26.6.1",
    "typing-extensions==4.16.0",
    "zope-interface==8.6",
]
