[project]
name = "fileshare"
version = "0.1.0"
description = "A P2P file transfer tool using Django Channels."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "attrs==25.4.0",
    "asgiref==3.11.0",
    "autobahn==25.10.2",
    "automat==25.4.16",
    "cffi==2.0.0",
    "channels==4.3.2",
    "constantly==23.10.4",
    "cryptography==45.0.6",
    "daphne==4.2.1",
    "django==6.0",
    "django-bootstrap5==25.3",
    "hyperlink==21.0.0",
    "idna==3.11",
    "incremental==24.11.0",
    "pyasn1==0.6.1",
    "pyasn1-modules==0.4.2",
    "pycparser==3.0",
    "python-dotenv==1.2.1",
    "pyopenssl==25.1.0",
    "service-identity==24.2.0",
    "sqlparse==0.5.5",
    "tomli==2.3.0",
    "twisted==25.5.0",
    "txaio==25.12.2",
    "typing-extensions==4.15.0",
    "zope-interface==8.2",
]
